export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Products } from './products/Products'
export { default as Technology } from './technology/Technology'
export { default as Solutions } from './solutions/Solutions'
