export { default as Article } from './article/Article'
export { default as CTA } from './cta/CTA'
export { default as Product } from './product/Product'
export { default as Navbar } from './navbar/Navbar'
export { default as Tech } from './tech/Tech'